### ISSUE TITLE
Calender Archive Does'nt expand when an Event is created in past.

### ISSUE THREAD

**Issue by manishucsd** [manishucsd/manishucsd.github.io#3]
When I tried creating an event for a past show in my calendar for say Aug 15th, 2015, then all the archive entries before Aug 15 th doesn't show up.

**Comment by vijayaggarwal** [comment]
The Event "Notorious Comedy" doesn't have a "place" specified. That was
causing the problem. Check now.

**Comment by manishucsd** [comment]
Thanks! past event works now. I remember trying past event with notorious and adding past event will mask everything before it. Maybe I am wrong, it works now!
